replicaCount: 1

metadata:
 name: ionic-app 
 label: ionic-app

hpa:
  metadata:
    name: ionic-appehpa
  spec:
    maxReplicas: 10
    minReplicas: 1
  metrics:
    pods:
      targetAverageValue: 50
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: ionic-app

image:
  name: ionic-app
  imageName: "ionic-app" 
  imagePullPolicy: Always
  maxSurge: 1
  maxUnavailable: 0
  requests:
    cpu: "400m"
    memory: "800Mi"
  limits:
    cpu: "900m"
    memory: "1000Mi"

service:
  serviceMetadata:
    name: ionic-app
  selector:
    selectorName: ionic-app
  servicePortConfiguration:
    name: ionic-app
    type: ClusterIP
    port: 8080
    targetPort: 8080


buildconfig:
  uri: "https://github.com/cumulus-bank/Mobile-App.git"
  branch: "master"
  name: "ionic-app"
  imagename: "ionic-app:latest"
  secret1: "edrftghj"
  secret2: "edrftghj"

imagestream:
  name:  ionic-app
  label: ionic-app


routes:
  host: "ionic-app-kubeapp.apps.9.30.210.207.nip.io"
  targetPort: 8080
  name: ionic-app
  weight: 100