apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cumulusionics.cumulusbank.com
spec:
  group: cumulusbank.com
  names:
    kind: CumulusIonic
    listKind: CumulusIonicList
    plural: cumulusionics
    singular: cumulusionic
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
