apiVersion: apps/v1
kind: Deployment
metadata:
  name: ionicapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ionicapp
  template:
    metadata:
      labels:
        name: ionicapp
    spec:
      serviceAccountName: ionicapp
      containers:
        - name: ionicapp
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ionicapp"
