kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
    labels:
        app: {{ .Values.imagestream.label }}
    name: {{ .Values.imagestream.name }}
    namespace: {{ .Values.metadata.namespace }}
    annotations:
        description: Keeps track of changes in the application image